- name: Install pip
  yum:
    name: '{{ item }}'
  with_items:
    - python34
    - python34-pip
    - python34-devel
  become: yes

- name: Install xkeysnail
  pip:
    name: xkeysnail
    executable: /usr/bin/pip3.4
  become: yes

- name: Set xkeysnail executable as /usr/bin/xkeysnail
  set_fact:
    xkeysnail_path: /usr/bin/xkeysnail

- name: Add user to group 'input'
  user:
    name: '{{ ansible_env.USER }}'
    groups:
      - input
    append: yes
  become: yes

- name: Add uinput group
  group:
    name: uinput
  become: yes

- name: Create 'xkeysnail' user to execute xkeysnail
  user:
    name: xkeysnail
    groups:
      - input
      - uinput
    create_home: no
    shell: /sbin/nologin
    append: yes
  become: yes

- name: Create config directory
  file:
    path: '{{ xkeysnail_config_dir }}'
    state: directory
  become: yes

- name: Place config file
  copy:
    dest: '{{ xkeysnail_config_dir }}'
    src: '{{ xkeysnail_config_file }}'
    mode: o+r
  become: yes

- name: Allow 'xkeysnail' user to access /dev/input/*
  lineinfile:
    path: '{{ item.path }}'
    line: '{{ item.line }}'
    create: yes
  with_items:
    - { 'path': '/etc/udev/rules.d/40-udev-xkeysnail.rules', 'line': 'KERNEL=="uinput", GROUP="uinput"' }
    - { 'path': '/etc/modules-load.d/uinput.conf', 'line': 'uinput' }
  become: yes

- name: Allow 'xkeysnail' user to execute xkeysnail without password
  lineinfile:
    path: /etc/sudoers.d/10-installer
    line: '{{ lookup("env", "USER") }} ALL=(ALL) ALL,(xkeysnail) NOPASSWD: {{ xkeysnail_path }}'
    create: yes
  become: yes

- name: Create start up script
  template:
    src: start-xkeysnail.sh
    dest: '{{ xkeysnail_config_dir }}/start-xkeysnail.sh'
    mode: a+x
  become: yes

- name: Register start up script
  template:
    src: xkeysnail.desktop
    dest: '{{ ansible_env.HOME }}/.config/autostart/xkeysnail.desktop'

